// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygniaaxgdsyzjmhtfeos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbmlhYXhnZHN5emptaHRmZW9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTk0NDMsImV4cCI6MjA2ODQzNTQ0M30.qcxwytBT3wcSDkGSgc0Fn7mUE1wi7yeQT9V41So3k6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});